"""Guard against stale generated front-end artifacts (issue #306).

``player.bundle.js`` and ``styles.css`` are *generated* by
``scripts/build_bundle.py`` / ``scripts/build_css.py`` from the source
modules under ``www/js/`` and ``www/css/src/``. They are committed so the
dev server, HACS install and CI all pick them up unchanged.

The cache-buster fingerprints whatever bytes are on disk — it cannot tell
that a source module changed but the committed bundle was never rebuilt.
So editing ``js/player-*.js`` or ``css/src/*.css`` without re-running the
build silently ships a stale artifact.

These tests reconstruct the expected artifact **in memory** (no disk write)
and assert it is byte-identical to the committed file. They are the unit
counterpart to the CI ``drift`` job (rebuild + ``git diff --exit-code``);
either one fails fast on stale artifacts.

Since #792 the same guard covers the pre-compressed ``.gz`` siblings, and there
it is doing more than tidiness. aiohttp's ``FileResponse`` serves ``<file>.gz``
*in place of* ``<file>`` whenever the sibling exists and the client sent
``Accept-Encoding: gzip`` — so a sibling that was not regenerated does not merely
go stale, it **wins over the fresh source** and the release ships the old code
with nothing in any log to say so. A ``.gz`` with no source, likewise, is a file
that can only ever be served by mistake.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "scripts"


def _load_script(name: str) -> ModuleType:
    """Import a scripts/<name>.py module by path (scripts/ isn't a package)."""
    path = SCRIPTS / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"_qz_{name}", path)
    assert spec and spec.loader, f"cannot load {path}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_player_bundle_in_sync() -> None:
    bb = _load_script("build_bundle")

    out_lines: list[str] = []
    out_lines.append(
        "/* AUTOGENERATED by scripts/build_bundle.py — do not edit by hand */"
    )
    out_lines.append(f"/* Bundles: {', '.join(bb.PLAYER_MODULES)} */")
    for module_name in bb.PLAYER_MODULES:
        src_path = bb.JS_DIR / module_name
        assert src_path.exists(), f"missing player module: {module_name}"
        out_lines.append(f"\n/* ============ {module_name} ============ */\n")
        out_lines.append(src_path.read_text("utf-8"))
    expected = "\n".join(out_lines)

    committed = bb.BUNDLE.read_text("utf-8")
    assert committed == expected, (
        "player.bundle.js is stale — a www/js/player-*.js module changed but "
        "the bundle was not rebuilt. Run: python3 scripts/build_bundle.py"
    )


def test_styles_css_in_sync() -> None:
    bc = _load_script("build_css")

    parts: list[str] = [bc.HEADER]
    for module_name in bc.CSS_MODULES:
        src_path = bc.SRC_DIR / module_name
        assert src_path.exists(), f"missing css module: {module_name}"
        parts.append(src_path.read_text("utf-8"))
    expected = "".join(parts)

    committed = bc.OUT.read_text("utf-8")
    assert committed == expected, (
        "styles.css is stale — a www/css/src/*.css module changed but the "
        "stylesheet was not rebuilt. Run: python3 scripts/build_css.py"
    )


# --- #792: the pre-compressed siblings aiohttp prefers over the source ---


def test_gzip_siblings_are_in_sync() -> None:
    """Recompress every declared target and compare bytes.

    The output is deterministic by construction (``mtime=0``, no filename in the
    header), so "the bytes differ" can only mean "the source changed and the
    sibling did not".
    """
    ag = _load_script("asset_gzip")

    stale: list[str] = []
    for rel in ag.GZIP_TARGETS:
        source = ag.WWW / rel
        assert source.is_file(), f"gzip target has no source: {rel}"
        sibling = ag.gzip_path(source)
        assert sibling.is_file(), (
            f"{rel}.gz is missing — aiohttp would serve the uncompressed file, "
            "which is only a lost 4x, but the drift guard is the point. "
            "Run: python3 scripts/build_gzip.py"
        )
        if sibling.read_bytes() != ag.gzip_bytes(source.read_bytes()):
            stale.append(rel)

    assert not stale, (
        f"stale .gz siblings: {stale}. aiohttp serves the sibling INSTEAD of the "
        "source, so these ship the previous version's bytes to every browser "
        "that sends Accept-Encoding. Run: python3 scripts/build_gzip.py"
    )


def test_no_orphan_gzip_siblings() -> None:
    """A ``.gz`` nobody generates is a file that can only be served by mistake.

    Two ways this bites: a target dropped from ``GZIP_TARGETS`` while its
    sibling stays behind (now frozen forever), and a ``.gz`` next to something
    that is *not* served from disk — ``sw.js`` and the HTML pages go out through
    ``server/views.py``, templated, so a sibling there would be an un-templated
    copy waiting for a routing change to surface it.
    """
    ag = _load_script("asset_gzip")

    expected = {ag.gzip_path(ag.WWW / rel) for rel in ag.GZIP_TARGETS}
    found = {p for p in ag.WWW.rglob("*.gz") if p.is_file()}
    orphans = sorted(str(p.relative_to(ag.WWW)) for p in found - expected)
    assert not orphans, (
        f"orphan .gz siblings under www/: {orphans}. Either add the source to "
        "GZIP_TARGETS in scripts/asset_gzip.py or delete the sibling."
    )


def test_the_generated_artifacts_carry_their_own_siblings() -> None:
    """build_bundle.py / build_css.py must write the .gz, not leave it to CI.

    Running one build script and committing is the normal path; if the sibling
    only appeared from a separate script, that path would ship a stale one.
    """
    for name in ("build_bundle", "build_css"):
        src = (SCRIPTS / f"{name}.py").read_text("utf-8")
        assert "write_gzip_sibling" in src, (
            f"scripts/{name}.py writes its artifact but not the .gz sibling that "
            "aiohttp will serve instead of it (#792)"
        )


def test_html_and_the_service_worker_are_not_pre_compressed() -> None:
    """They are never served from disk, so a sibling could only ever be wrong.

    ``server/views.py`` reads them, substitutes ``{{VERSION}}`` /
    ``{{ASSET_VER}}`` / ``{{DEFAULT_LANG}}`` and answers with a ``web.Response``;
    its routes are registered ahead of the static handler. A ``.gz`` here would
    hold an un-templated copy.
    """
    ag = _load_script("asset_gzip")
    for rel in ag.GZIP_TARGETS:
        assert not rel.endswith(".html"), f"{rel} is templated, not served from disk"
        assert not rel.endswith("sw.js"), f"{rel} is templated, not served from disk"


def test_incompressible_binaries_are_left_alone() -> None:
    """woff2 and png come out *bigger*; a sibling would be a slower download."""
    ag = _load_script("asset_gzip")
    for rel in ag.GZIP_TARGETS:
        assert not rel.endswith((".woff2", ".png", ".jpg", ".webp")), (
            f"{rel} is already compressed — gzipping it adds bytes"
        )
