"""Guard against stale generated front-end artifacts (issue #306).

``player.bundle.js`` and ``styles.css`` are *generated* by
``scripts/build_bundle.py`` / ``scripts/build_css.py`` from the source
modules under ``www/js/`` and ``www/css/src/``. They are committed so the
dev server, HACS install and CI all pick them up unchanged.

The cache-buster fingerprints whatever bytes are on disk — it cannot tell
that a source module changed but the committed bundle was never rebuilt.
So editing ``js/player-*.js`` or ``css/src/*.css`` without re-running the
build silently ships a stale artifact.

These tests reconstruct the expected artifact **in memory** (no disk write)
and assert it is byte-identical to the committed file. They are the unit
counterpart to the CI ``drift`` job (rebuild + ``git diff --exit-code``);
either one fails fast on stale artifacts.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "scripts"


def _load_script(name: str) -> ModuleType:
    """Import a scripts/<name>.py module by path (scripts/ isn't a package)."""
    path = SCRIPTS / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"_qz_{name}", path)
    assert spec and spec.loader, f"cannot load {path}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_player_bundle_in_sync() -> None:
    bb = _load_script("build_bundle")

    out_lines: list[str] = []
    out_lines.append(
        "/* AUTOGENERATED by scripts/build_bundle.py — do not edit by hand */"
    )
    out_lines.append(f"/* Bundles: {', '.join(bb.PLAYER_MODULES)} */")
    for module_name in bb.PLAYER_MODULES:
        src_path = bb.JS_DIR / module_name
        assert src_path.exists(), f"missing player module: {module_name}"
        out_lines.append(f"\n/* ============ {module_name} ============ */\n")
        out_lines.append(src_path.read_text("utf-8"))
    expected = "\n".join(out_lines)

    committed = bb.BUNDLE.read_text("utf-8")
    assert committed == expected, (
        "player.bundle.js is stale — a www/js/player-*.js module changed but "
        "the bundle was not rebuilt. Run: python3 scripts/build_bundle.py"
    )


def test_styles_css_in_sync() -> None:
    bc = _load_script("build_css")

    parts: list[str] = [bc.HEADER]
    for module_name in bc.CSS_MODULES:
        src_path = bc.SRC_DIR / module_name
        assert src_path.exists(), f"missing css module: {module_name}"
        parts.append(src_path.read_text("utf-8"))
    expected = "".join(parts)

    committed = bc.OUT.read_text("utf-8")
    assert committed == expected, (
        "styles.css is stale — a www/css/src/*.css module changed but the "
        "stylesheet was not rebuilt. Run: python3 scripts/build_css.py"
    )
