"""Constants for Quizify."""

DOMAIN = "quizify"

# Game configuration
MAX_PLAYERS = 20
MIN_PLAYERS = 2
DEFAULT_ROUND_DURATION = 30  # seconds
ROUND_DURATION_MIN = 10  # seconds
ROUND_DURATION_MAX = 60  # seconds
MAX_NAME_LENGTH = 20
MIN_NAME_LENGTH = 1
LOBBY_DISCONNECT_GRACE_PERIOD = 5  # seconds before removing disconnected player

# Question difficulty levels
DIFFICULTY_EASY = "easy"
DIFFICULTY_MEDIUM = "medium"
DIFFICULTY_HARD = "hard"
DIFFICULTY_DEFAULT = DIFFICULTY_MEDIUM

# Error codes
ERR_NAME_TAKEN = "NAME_TAKEN"
ERR_NAME_INVALID = "NAME_INVALID"
ERR_GAME_NOT_STARTED = "GAME_NOT_STARTED"
ERR_GAME_ALREADY_STARTED = "GAME_ALREADY_STARTED"
ERR_GAME_ENDED = "GAME_ENDED"
ERR_NOT_ADMIN = "NOT_ADMIN"
ERR_ADMIN_EXISTS = "ADMIN_EXISTS"
ERR_ROUND_EXPIRED = "ROUND_EXPIRED"
ERR_ALREADY_SUBMITTED = "ALREADY_SUBMITTED"
ERR_NOT_IN_GAME = "NOT_IN_GAME"
ERR_INVALID_ACTION = "INVALID_ACTION"
ERR_GAME_FULL = "GAME_FULL"
ERR_NO_QUESTIONS_REMAINING = "NO_QUESTIONS_REMAINING"
ERR_SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
ERR_SESSION_TAKEOVER = "SESSION_TAKEOVER"
ERR_ADMIN_CANNOT_LEAVE = "ADMIN_CANNOT_LEAVE"

# Question bank configuration
QUESTIONS_DIR = "quizify/questions"
