#!/usr/bin/env python3
"""Concatenate the player JS modules into a single player.bundle.js.

The player page used to load 8 separate scripts sequentially. On a
phone over 4G the waterfall noticeably delays interactive. Each module
is already a closed-over IIFE that publishes its API on `window.*`, so
plain concatenation is safe — no module system, no transforms.

Run once before each release; the output is committed so the dev
server and CI both pick it up.

    python3 scripts/build_bundle.py

The bundle filename has a content-hash suffix appended so cache
invalidation works without touching every HTML file's ?v= query.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
JS_DIR = REPO / "custom_components" / "quizify" / "www" / "js"

# Order matters — modules later in the list may reference earlier
# globals (QuizifyPlayerUtils, QuizifyPlayerGame). Mirror what
# player.html loads today, minus i18n.js / utils.js / vendor (those
# stay separate because they're shared with admin/dashboard).
PLAYER_MODULES = [
    "player-utils.js",
    "player-sound.js",
    "player-a11y.js",
    "player-lobby.js",
    "player-team.js",
    "player-reveal.js",
    "player-end.js",
    "player-lightning.js",
    "player-hotseat.js",
    "player-game.js",
    "player-core.js",
]

BUNDLE = JS_DIR / "player.bundle.js"


def build_bundle() -> Path:
    out_lines: list[str] = []
    out_lines.append("/* AUTOGENERATED by scripts/build_bundle.py — do not edit by hand */")
    out_lines.append(f"/* Bundles: {', '.join(PLAYER_MODULES)} */")

    for name in PLAYER_MODULES:
        path = JS_DIR / name
        if not path.exists():
            print(f"  skip (missing): {name}", file=sys.stderr)
            continue
        src = path.read_text("utf-8")
        out_lines.append(f"\n/* ============ {name} ============ */\n")
        out_lines.append(src)

    text = "\n".join(out_lines)
    BUNDLE.write_text(text, "utf-8")

    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:10]
    print(f"Wrote {BUNDLE.relative_to(REPO)} ({len(text):,} bytes, sha1:{digest})")
    return BUNDLE


if __name__ == "__main__":
    build_bundle()
