#!/usr/bin/env python3
"""Concatenate the CSS source modules into a single served styles.css.

styles.css used to be one ~6.7k-line god-file. It is now split into
small per-screen / per-component modules under www/css/src/ for
maintainability. CSS has no module system, so the served file is just
the modules concatenated **in the exact original cascade order** —
order matters, later rules override earlier ones.

Run once before each release; the output (styles.css) is committed so
the dev server, HACS install and CI all pick it up unchanged. The HTML
keeps loading the single styles.css, so the cache-buster ?v= query is
unaffected.

    python3 scripts/build_css.py

This is the CSS analogue of scripts/build_bundle.py (player JS).
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from asset_gzip import write_gzip_sibling  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
CSS_DIR = REPO / "custom_components" / "quizify" / "www" / "css"
SRC_DIR = CSS_DIR / "src"

# Order matters — this is the cascade order. The modules are byte-exact
# slices of the original styles.css, split at the existing section
# banners. Concatenating them in this order reproduces the original
# rules in the original order (only difference: the header comment
# prepended below, which is inert CSS).
CSS_MODULES = [
    "00-tokens.css",      # Design tokens, dark mode
    "01-base.css",        # Base styles, brand wordmark, layout, header
    "02-shared.css",      # Buttons, inputs, cards, chips, pack-cards, settings
    "03-question.css",    # Timer bar, question display, answers, power-up, score, fun fact
    "04-lobby.css",       # Lobby, QR code, self-join, admin setup + question preview
    "05-finale.css",      # Leaderboard, final leaderboard, podium, awards
    "06-admin.css",       # Launcher, modal, glow/badge/utility helpers
    "07-player.css",      # Player END/GAME/REVEAL/LOBBY views + setup/lobby variants + modals/misc
    "08-responsive.css",  # Responsive, reduced motion, reveal grids, result page, finale, community pack
    # Last on purpose: 09 redefines the --font-size-* tokens from 00-tokens
    # under .a11y. Both selectors have the same specificity and hit the same
    # element (<html>), so only source order makes the override win (#372).
    "09-a11y.css",        # Accessibility mode — larger type, motion held still
]

OUT = CSS_DIR / "styles.css"

HEADER = (
    "/* AUTOGENERATED by scripts/build_css.py — do not edit by hand. */\n"
    "/* Edit the modules in www/css/src/ then run python3 scripts/build_css.py */\n"
)


def build_css() -> Path:
    parts: list[str] = [HEADER]
    for name in CSS_MODULES:
        path = SRC_DIR / name
        if not path.exists():
            print(f"  ERROR (missing module): {name}", file=sys.stderr)
            sys.exit(1)
        parts.append(path.read_text("utf-8"))

    text = "".join(parts)
    OUT.write_text(text, "utf-8")

    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:10]
    print(f"Wrote {OUT.relative_to(REPO)} ({len(text):,} bytes, sha1:{digest})")

    # Same reason as in build_bundle.py: the .gz sibling wins over this file
    # when a browser sends Accept-Encoding, so it is part of the build, not an
    # optional extra step (#792).
    gz = write_gzip_sibling(OUT)
    print(f"Wrote {gz.relative_to(REPO)} ({gz.stat().st_size:,} bytes)")
    return OUT


if __name__ == "__main__":
    build_css()
