#!/usr/bin/env python3
"""Concatenate the front-end JS modules into the two committed bundles.

The player page used to load 8 separate scripts sequentially. On a
phone over 4G the waterfall noticeably delays interactive. Each module
is already a closed-over IIFE that publishes its API on `window.*`, so
plain concatenation is safe — no module system, no transforms.

Since #787 there is a second bundle: ``common.bundle.js``, the socket
lifecycle (``client-core.js``) and the renderers all three surfaces share
(``render-shared.js``). All three pages load it, ahead of anything that uses
it, which is why it is its own file rather than a prefix of the player bundle
— the television and the host page do not load the player bundle at all.

Run once before each release; the output is committed so the dev
server and CI both pick it up.

    python3 scripts/build_bundle.py

The bundle filename has a content-hash suffix appended so cache
invalidation works without touching every HTML file's ?v= query.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from asset_gzip import write_gzip_sibling  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
JS_DIR = REPO / "custom_components" / "quizify" / "www" / "js"

# Order matters — modules later in the list may reference earlier
# globals (QuizifyPlayerUtils, QuizifyPlayerGame). Mirror what
# player.html loads today, minus i18n.js / utils.js / vendor (those
# stay separate because they're shared with admin/dashboard).
PLAYER_MODULES = [
    "player-utils.js",
    "player-sound.js",
    "player-a11y.js",
    "player-lobby.js",
    "player-team.js",
    "player-reveal.js",
    "player-end.js",
    "player-lightning.js",
    "player-hotseat.js",
    "player-game.js",
    "player-core.js",
]

# The shared half (#787), loaded by dashboard.html, admin.html and
# player.html alike. client-core.js first: render-shared.js does not depend on
# it today, but the load order on the pages is the same one, and keeping the
# bundle in that order means the file reads like the pages do.
COMMON_MODULES = [
    "client-core.js",
    "render-shared.js",
]

BUNDLE = JS_DIR / "player.bundle.js"
COMMON_BUNDLE = JS_DIR / "common.bundle.js"


def _concat(modules: list[str]) -> str:
    out_lines: list[str] = []
    out_lines.append(
        "/* AUTOGENERATED by scripts/build_bundle.py — do not edit by hand */"
    )
    out_lines.append(f"/* Bundles: {', '.join(modules)} */")

    for name in modules:
        path = JS_DIR / name
        if not path.exists():
            print(f"  skip (missing): {name}", file=sys.stderr)
            continue
        src = path.read_text("utf-8")
        out_lines.append(f"\n/* ============ {name} ============ */\n")
        out_lines.append(src)

    return "\n".join(out_lines)


def _write(out: Path, modules: list[str]) -> Path:
    text = _concat(modules)
    out.write_text(text, "utf-8")

    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:10]
    print(f"Wrote {out.relative_to(REPO)} ({len(text):,} bytes, sha1:{digest})")

    # aiohttp serves <file>.gz in place of <file> whenever it exists, so the
    # sibling has to be rewritten in the same breath as the bundle — a stale one
    # would be served instead of this fresh output, silently (#792).
    gz = write_gzip_sibling(out)
    print(f"Wrote {gz.relative_to(REPO)} ({gz.stat().st_size:,} bytes)")
    return out


def build_bundle() -> Path:
    _write(COMMON_BUNDLE, COMMON_MODULES)
    return _write(BUNDLE, PLAYER_MODULES)


if __name__ == "__main__":
    build_bundle()
